---
title: "How did the change of the ecosystem affect the numbats?"
author: 
  - Bayazit, Gül Sena[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080472, [Github Repo](https://github.com/GulSenaBayazit/MidTerm1.git)

# Important Information About Midterm

\colorbox{BurntOrange}{WRITE YOUR GITHUB REPO LINK ON LINE 35 IN THIS FILE!}

**Project Proposal submisson will be done by uploading a zip file to the ekampus system along with the Github repo link. If you do not upload a zip file to the system and do not provide a Github repo link, you will be deemed not to have entered the midterm and final exams.**

**You must upload your project folder (`YourStudentID.zip` file) to *ekampus.ankara.edu.tr* until 16 April 2023, 23:59.**

\colorbox{WildStrawberry}{Read the README.md file in the project folder for more information.}

# Introduction
This outline has been created to assist you in writing your project assignment. You should cite all the sources you use, articles, presentations, projects, etc. Quoting and referencing gives readers the opportunity to access the resources you refer. **Even though you use your own words, if you are conveying the ideas of others in your work, you have to document the source of these ideas. Otherwise, you are committing academic plagiarism.** For example, you can refer to @chambers:2020 for academic writing rules. You can find lots of online resources on this topic.

The sections in your project assignment must necessarily include the sections in this text (except the first section, of course). Apart from the sections used here, you can use different subsections. When writing your project, use this file as a draft and adapt its content to your purposes.

In this section, mention the purpose and importance of your work in a few paragraphs.

Question: How did the change of the ecosystem affect the numbats?

The numbat is a small marsupial that is native to Western Australia and is known for its unique diet of termites. However, like many other species, numbats have been significantly impacted by changes to their ecosystem. The primary factors that have affected their population are habitat loss and fragmentation, which are primarily caused by human activities such as deforestation, land-use changes, and agriculture. These changes have drastically altered the numbat's natural habitat, leading to a decline in their numbers. As such, understanding how these changes have affected numbats is crucial to developing effective conservation strategies to protect this unique species. In this response, we will explore the different ways in which the change of the ecosystem has impacted numbats.

## Literature Review

In this section, discuss the articles you have read on the subject by giving references. This is a narrative citation @waterhouse:1836. This one is a parenthetical citation [@waterhouse:1836]. **Do not summarize each article individually under a separate title.** In the literature review section, **at least four** articles must be cited [@chambers:2020; @bourguignon:2017; @waterhouse:1836; @lawler:2019].

Numbats are a unique species of marsupial that feed on termites and inhabit Western Australia. However, ecological changes such as human activities significantly impact the numbat population. The key factors affecting the numbat population are habitat loss and fragmentation, which cause significant changes in natural habitats due to factors such as deforestation, agriculture, and land use changes caused by human activities. These changes in the numbat's habitat cause a decrease in their numbers. Therefore, to develop effective conservation strategies for numbat protection, it is essential to understand how these changes have affected them.

Research shows that numbat populations have declined due to factors such as habitat loss and fragmentation, fires, and invasive species caused by changes in the ecosystem. In addition, studies are being conducted on how numbat survive in fragmented landscapes, how they select their habitats, and how their populations change. These studies will help determine the steps to be taken for the conservation of numbats.

In conclusion, reducing habitat loss and fragmentation, minimizing the effects of fires, and preventing the invasion of foreign species are necessary to protect the numbat population. Therefore, efforts should be made to protect and sustainable manage the numbat's habitats.

**References section is created automatically by Rmarkdown. There is no need to change the references section in the draft file.**

**_You shouldn't delete the last 3 lines. Those lines are required for References section._**

\newpage
# References {#references}
<div id="refs"></div>


